var timezoneData = [
  { offset: "+00", gtm: "GTM+00:00", city: "Africa/Abidjan" },
  { offset: "+00", gtm: "GTM+00:00", city: "Africa/Accra" },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Africa/Addis_Ababa",
  },
  { offset: "+01", gtm: "GTM+01:00", city: "Africa/Algiers" },
  { offset: "+03", gtm: "GTM+03:00", city: "Africa/Asmara" },
  { offset: "+03", gtm: "GTM+03:00", city: "Africa/Asmera" },
  { offset: "+00", gtm: "GTM+00:00", city: "Africa/Bamako" },
  { offset: "+01", gtm: "GTM+01:00", city: "Africa/Bangui" },
  { offset: "+00", gtm: "GTM+00:00", city: "Africa/Banjul" },
  { offset: "+00", gtm: "GTM+00:00", city: "Africa/Bissau" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Africa/Blantyre",
  },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Africa/Brazzaville",
  },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Africa/Bujumbura",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Africa/Cairo" },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Africa/Casablanca",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Africa/Ceuta" },
  { offset: "+00", gtm: "GTM+00:00", city: "Africa/Conakry" },
  { offset: "+00", gtm: "GTM+00:00", city: "Africa/Dakar" },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Africa/Dar_es_Salaam",
  },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Africa/Djibouti",
  },
  { offset: "+01", gtm: "GTM+01:00", city: "Africa/Douala" },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Africa/El_Aaiun",
  },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "Africa/Freetown",
  },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Africa/Gaborone",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Africa/Harare" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Africa/Johannesburg",
  },
  { offset: "+03", gtm: "GTM+03:00", city: "Africa/Juba" },
  { offset: "+03", gtm: "GTM+03:00", city: "Africa/Kampala" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Africa/Khartoum",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Africa/Kigali" },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Africa/Kinshasa",
  },
  { offset: "+01", gtm: "GTM+01:00", city: "Africa/Lagos" },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Africa/Libreville",
  },
  { offset: "+00", gtm: "GTM+00:00", city: "Africa/Lome" },
  { offset: "+01", gtm: "GTM+01:00", city: "Africa/Luanda" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Africa/Lubumbashi",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Africa/Lusaka" },
  { offset: "+01", gtm: "GTM+01:00", city: "Africa/Malabo" },
  { offset: "+02", gtm: "GTM+02:00", city: "Africa/Maputo" },
  { offset: "+02", gtm: "GTM+02:00", city: "Africa/Maseru" },
  { offset: "+02", gtm: "GTM+02:00", city: "Africa/Mbabane" },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Africa/Mogadishu",
  },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "Africa/Monrovia",
  },
  { offset: "+03", gtm: "GTM+03:00", city: "Africa/Nairobi" },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Africa/Ndjamena",
  },
  { offset: "+01", gtm: "GTM+01:00", city: "Africa/Niamey" },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "Africa/Nouakchott",
  },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "Africa/Ouagadougou",
  },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Africa/Porto-Novo",
  },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "Africa/Sao_Tome",
  },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "Africa/Timbuktu",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Africa/Tripoli" },
  { offset: "+01", gtm: "GTM+01:00", city: "Africa/Tunis" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Africa/Windhoek",
  },
  { offset: "-09", gtm: "GTM-09:00", city: "America/Adak" },
  {
    offset: "-08",
    gtm: "GTM-08:00",
    city: "America/Anchorage",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Anguilla",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Antigua",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Araguaina",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/Buenos_Aires",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/Catamarca",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/ComodRivadavia",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/Cordoba",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/Jujuy",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/La_Rioja",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/Mendoza",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/Rio_Gallegos",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/Salta",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/San_Juan",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/San_Luis",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/Tucuman",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Argentina/Ushuaia",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "America/Aruba" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Asuncion",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Atikokan",
  },
  { offset: "-09", gtm: "GTM-09:00", city: "America/Atka" },
  { offset: "-03", gtm: "GTM-03:00", city: "America/Bahia" },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Bahia_Banderas",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Barbados",
  },
  { offset: "-03", gtm: "GTM-03:00", city: "America/Belem" },
  { offset: "-06", gtm: "GTM-06:00", city: "America/Belize" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Blanc-Sablon",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Boa_Vista",
  },
  { offset: "-05", gtm: "GTM-05:00", city: "America/Bogota" },
  { offset: "-06", gtm: "GTM-06:00", city: "America/Boise" },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Buenos_Aires",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Cambridge_Bay",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Campo_Grande",
  },
  { offset: "-05", gtm: "GTM-05:00", city: "America/Cancun" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Caracas",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Catamarca",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Cayenne",
  },
  { offset: "-05", gtm: "GTM-05:00", city: "America/Cayman" },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Chicago",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Chihuahua",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Coral_Harbour",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Cordoba",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Costa_Rica",
  },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Creston",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "America/Cuiaba" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Curacao",
  },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "America/Danmarkshavn",
  },
  { offset: "-07", gtm: "GTM-07:00", city: "America/Dawson" },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Dawson_Creek",
  },
  { offset: "-06", gtm: "GTM-06:00", city: "America/Denver" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Detroit",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Dominica",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Edmonton",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Eirunepe",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/El_Salvador",
  },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Ensenada",
  },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Fort_Nelson",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Fort_Wayne",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Fortaleza",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Glace_Bay",
  },
  {
    offset: "-02",
    gtm: "GTM-02:00",
    city: "America/Godthab",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Goose_Bay",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Grand_Turk",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Grenada",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Guadeloupe",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Guatemala",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Guayaquil",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "America/Guyana" },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Halifax",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "America/Havana" },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Hermosillo",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Indiana/Indianapolis",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Indiana/Knox",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Indiana/Marengo",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Indiana/Petersburg",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Indiana/Tell_City",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Indiana/Vevay",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Indiana/Vincennes",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Indiana/Winamac",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Indianapolis",
  },
  { offset: "-06", gtm: "GTM-06:00", city: "America/Inuvik" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Iqaluit",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Jamaica",
  },
  { offset: "-03", gtm: "GTM-03:00", city: "America/Jujuy" },
  { offset: "-08", gtm: "GTM-08:00", city: "America/Juneau" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Kentucky/Louisville",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Kentucky/Monticello",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Knox_IN",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Kralendijk",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "America/La_Paz" },
  { offset: "-05", gtm: "GTM-05:00", city: "America/Lima" },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Los_Angeles",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Louisville",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Lower_Princes",
  },
  { offset: "-03", gtm: "GTM-03:00", city: "America/Maceio" },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Managua",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "America/Manaus" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Marigot",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Martinique",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Matamoros",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Mazatlan",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Mendoza",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Menominee",
  },
  { offset: "-05", gtm: "GTM-05:00", city: "America/Merida" },
  {
    offset: "-08",
    gtm: "GTM-08:00",
    city: "America/Metlakatla",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Mexico_City",
  },
  {
    offset: "-02",
    gtm: "GTM-02:00",
    city: "America/Miquelon",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Moncton",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Monterrey",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Montevideo",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Montreal",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Montserrat",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "America/Nassau" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/New_York",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Nipigon",
  },
  { offset: "-08", gtm: "GTM-08:00", city: "America/Nome" },
  {
    offset: "-02",
    gtm: "GTM-02:00",
    city: "America/Noronha",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/North_Dakota/Beulah",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/North_Dakota/Center",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/North_Dakota/New_Salem",
  },
  { offset: "-02", gtm: "GTM-02:00", city: "America/Nuuk" },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Ojinaga",
  },
  { offset: "-05", gtm: "GTM-05:00", city: "America/Panama" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Pangnirtung",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Paramaribo",
  },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Phoenix",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Port-au-Prince",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Port_of_Spain",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Porto_Acre",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Porto_Velho",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Puerto_Rico",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Punta_Arenas",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Rainy_River",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Rankin_Inlet",
  },
  { offset: "-03", gtm: "GTM-03:00", city: "America/Recife" },
  { offset: "-06", gtm: "GTM-06:00", city: "America/Regina" },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Resolute",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Rio_Branco",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Rosario",
  },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Santa_Isabel",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Santarem",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Santiago",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Santo_Domingo",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "America/Sao_Paulo",
  },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "America/Scoresbysund",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Shiprock",
  },
  { offset: "-08", gtm: "GTM-08:00", city: "America/Sitka" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/St_Barthelemy",
  },
  {
    offset: "-02",
    gtm: "GTM-02:30",
    city: "America/St_Johns",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/St_Kitts",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/St_Lucia",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/St_Thomas",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/St_Vincent",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Swift_Current",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Tegucigalpa",
  },
  { offset: "-03", gtm: "GTM-03:00", city: "America/Thule" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Thunder_Bay",
  },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Tijuana",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Toronto",
  },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "America/Tortola",
  },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Vancouver",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "America/Virgin" },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "America/Whitehorse",
  },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "America/Winnipeg",
  },
  {
    offset: "-08",
    gtm: "GTM-08:00",
    city: "America/Yakutat",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "America/Yellowknife",
  },
  {
    offset: "+08",
    gtm: "GTM+08:00",
    city: "Antarctica/Casey",
  },
  {
    offset: "+07",
    gtm: "GTM+07:00",
    city: "Antarctica/Davis",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Antarctica/DumontDUrville",
  },
  {
    offset: "+11",
    gtm: "GTM+11:00",
    city: "Antarctica/Macquarie",
  },
  {
    offset: "+05",
    gtm: "GTM+05:00",
    city: "Antarctica/Mawson",
  },
  {
    offset: "+12",
    gtm: "GTM+12:00",
    city: "Antarctica/McMurdo",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "Antarctica/Palmer",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "Antarctica/Rothera",
  },
  {
    offset: "+12",
    gtm: "GTM+12:00",
    city: "Antarctica/South_Pole",
  },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Antarctica/Syowa",
  },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Antarctica/Troll",
  },
  {
    offset: "+06",
    gtm: "GTM+06:00",
    city: "Antarctica/Vostok",
  },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Arctic/Longyearbyen",
  },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Aden" },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Almaty" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Amman" },
  { offset: "+12", gtm: "GTM+12:00", city: "Asia/Anadyr" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Aqtau" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Aqtobe" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Ashgabat" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Ashkhabad" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Atyrau" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Baghdad" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Bahrain" },
  { offset: "+04", gtm: "GTM+04:00", city: "Asia/Baku" },
  { offset: "+07", gtm: "GTM+07:00", city: "Asia/Bangkok" },
  { offset: "+07", gtm: "GTM+07:00", city: "Asia/Barnaul" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Beirut" },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Bishkek" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Brunei" },
  { offset: "+05", gtm: "GTM+05:30", city: "Asia/Calcutta" },
  { offset: "+09", gtm: "GTM+09:00", city: "Asia/Chita" },
  {
    offset: "+08",
    gtm: "GTM+08:00",
    city: "Asia/Choibalsan",
  },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Chongqing" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Chungking" },
  { offset: "+05", gtm: "GTM+05:30", city: "Asia/Colombo" },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Dacca" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Damascus" },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Dhaka" },
  { offset: "+09", gtm: "GTM+09:00", city: "Asia/Dili" },
  { offset: "+04", gtm: "GTM+04:00", city: "Asia/Dubai" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Dushanbe" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Famagusta" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Gaza" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Harbin" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Hebron" },
  {
    offset: "+07",
    gtm: "GTM+07:00",
    city: "Asia/Ho_Chi_Minh",
  },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Hong_Kong" },
  { offset: "+07", gtm: "GTM+07:00", city: "Asia/Hovd" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Irkutsk" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Istanbul" },
  { offset: "+07", gtm: "GTM+07:00", city: "Asia/Jakarta" },
  { offset: "+09", gtm: "GTM+09:00", city: "Asia/Jayapura" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Jerusalem" },
  { offset: "+04", gtm: "GTM+04:30", city: "Asia/Kabul" },
  { offset: "+12", gtm: "GTM+12:00", city: "Asia/Kamchatka" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Karachi" },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Kashgar" },
  { offset: "+05", gtm: "GTM+05:45", city: "Asia/Kathmandu" },
  { offset: "+05", gtm: "GTM+05:45", city: "Asia/Katmandu" },
  { offset: "+09", gtm: "GTM+09:00", city: "Asia/Khandyga" },
  { offset: "+05", gtm: "GTM+05:30", city: "Asia/Kolkata" },
  {
    offset: "+07",
    gtm: "GTM+07:00",
    city: "Asia/Krasnoyarsk",
  },
  {
    offset: "+08",
    gtm: "GTM+08:00",
    city: "Asia/Kuala_Lumpur",
  },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Kuching" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Kuwait" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Macao" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Macau" },
  { offset: "+11", gtm: "GTM+11:00", city: "Asia/Magadan" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Makassar" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Manila" },
  { offset: "+04", gtm: "GTM+04:00", city: "Asia/Muscat" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Nicosia" },
  {
    offset: "+07",
    gtm: "GTM+07:00",
    city: "Asia/Novokuznetsk",
  },
  {
    offset: "+07",
    gtm: "GTM+07:00",
    city: "Asia/Novosibirsk",
  },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Omsk" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Oral" },
  {
    offset: "+07",
    gtm: "GTM+07:00",
    city: "Asia/Phnom_Penh",
  },
  { offset: "+07", gtm: "GTM+07:00", city: "Asia/Pontianak" },
  { offset: "+09", gtm: "GTM+09:00", city: "Asia/Pyongyang" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Qatar" },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Qostanay" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Qyzylorda" },
  { offset: "+06", gtm: "GTM+06:30", city: "Asia/Rangoon" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Riyadh" },
  { offset: "+07", gtm: "GTM+07:00", city: "Asia/Saigon" },
  { offset: "+11", gtm: "GTM+11:00", city: "Asia/Sakhalin" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Samarkand" },
  { offset: "+09", gtm: "GTM+09:00", city: "Asia/Seoul" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Shanghai" },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Singapore" },
  {
    offset: "+11",
    gtm: "GTM+11:00",
    city: "Asia/Srednekolymsk",
  },
  { offset: "+08", gtm: "GTM+08:00", city: "Asia/Taipei" },
  { offset: "+05", gtm: "GTM+05:00", city: "Asia/Tashkent" },
  { offset: "+04", gtm: "GTM+04:00", city: "Asia/Tbilisi" },
  { offset: "+04", gtm: "GTM+04:30", city: "Asia/Tehran" },
  { offset: "+03", gtm: "GTM+03:00", city: "Asia/Tel_Aviv" },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Thimbu" },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Thimphu" },
  { offset: "+09", gtm: "GTM+09:00", city: "Asia/Tokyo" },
  { offset: "+07", gtm: "GTM+07:00", city: "Asia/Tomsk" },
  {
    offset: "+08",
    gtm: "GTM+08:00",
    city: "Asia/Ujung_Pandang",
  },
  {
    offset: "+08",
    gtm: "GTM+08:00",
    city: "Asia/Ulaanbaatar",
  },
  {
    offset: "+08",
    gtm: "GTM+08:00",
    city: "Asia/Ulan_Bator",
  },
  { offset: "+06", gtm: "GTM+06:00", city: "Asia/Urumqi" },
  { offset: "+10", gtm: "GTM+10:00", city: "Asia/Ust-Nera" },
  { offset: "+07", gtm: "GTM+07:00", city: "Asia/Vientiane" },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Asia/Vladivostok",
  },
  { offset: "+09", gtm: "GTM+09:00", city: "Asia/Yakutsk" },
  { offset: "+06", gtm: "GTM+06:30", city: "Asia/Yangon" },
  {
    offset: "+05",
    gtm: "GTM+05:00",
    city: "Asia/Yekaterinburg",
  },
  { offset: "+04", gtm: "GTM+04:00", city: "Asia/Yerevan" },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "Atlantic/Azores",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "Atlantic/Bermuda",
  },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Atlantic/Canary",
  },
  {
    offset: "-01",
    gtm: "GTM-01:00",
    city: "Atlantic/Cape_Verde",
  },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Atlantic/Faeroe",
  },
  { offset: "+01", gtm: "GTM+01:00", city: "Atlantic/Faroe" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Atlantic/Jan_Mayen",
  },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Atlantic/Madeira",
  },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "Atlantic/Reykjavik",
  },
  {
    offset: "-02",
    gtm: "GTM-02:00",
    city: "Atlantic/South_Georgia",
  },
  {
    offset: "+00",
    gtm: "GTM+00:00",
    city: "Atlantic/St_Helena",
  },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "Atlantic/Stanley",
  },
  { offset: "+10", gtm: "GTM+10:00", city: "Australia/ACT" },
  {
    offset: "+09",
    gtm: "GTM+09:30",
    city: "Australia/Adelaide",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Brisbane",
  },
  {
    offset: "+09",
    gtm: "GTM+09:30",
    city: "Australia/Broken_Hill",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Canberra",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Currie",
  },
  {
    offset: "+09",
    gtm: "GTM+09:30",
    city: "Australia/Darwin",
  },
  {
    offset: "+08",
    gtm: "GTM+08:45",
    city: "Australia/Eucla",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Hobart",
  },
  { offset: "+10", gtm: "GTM+10:30", city: "Australia/LHI" },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Lindeman",
  },
  {
    offset: "+10",
    gtm: "GTM+10:30",
    city: "Australia/Lord_Howe",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Melbourne",
  },
  { offset: "+10", gtm: "GTM+10:00", city: "Australia/NSW" },
  {
    offset: "+09",
    gtm: "GTM+09:30",
    city: "Australia/North",
  },
  {
    offset: "+08",
    gtm: "GTM+08:00",
    city: "Australia/Perth",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Queensland",
  },
  {
    offset: "+09",
    gtm: "GTM+09:30",
    city: "Australia/South",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Sydney",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Tasmania",
  },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Australia/Victoria",
  },
  { offset: "+08", gtm: "GTM+08:00", city: "Australia/West" },
  {
    offset: "+09",
    gtm: "GTM+09:30",
    city: "Australia/Yancowinna",
  },
  { offset: "-05", gtm: "GTM-05:00", city: "Brazil/Acre" },
  {
    offset: "-02",
    gtm: "GTM-02:00",
    city: "Brazil/DeNoronha",
  },
  { offset: "-03", gtm: "GTM-03:00", city: "Brazil/East" },
  { offset: "-04", gtm: "GTM-04:00", city: "Brazil/West" },
  { offset: "+02", gtm: "GTM+02:00", city: "CET" },
  { offset: "-05", gtm: "GTM-05:00", city: "CST6CDT" },
  {
    offset: "-03",
    gtm: "GTM-03:00",
    city: "Canada/Atlantic",
  },
  { offset: "-05", gtm: "GTM-05:00", city: "Canada/Central" },
  { offset: "-04", gtm: "GTM-04:00", city: "Canada/Eastern" },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "Canada/Mountain",
  },
  {
    offset: "-02",
    gtm: "GTM-02:30",
    city: "Canada/Newfoundland",
  },
  { offset: "-07", gtm: "GTM-07:00", city: "Canada/Pacific" },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "Canada/Saskatchewan",
  },
  { offset: "-07", gtm: "GTM-07:00", city: "Canada/Yukon" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "Chile/Continental",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "Chile/EasterIsland",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "Cuba" },
  { offset: "+03", gtm: "GTM+03:00", city: "EET" },
  { offset: "-05", gtm: "GTM-05:00", city: "EST" },
  { offset: "-04", gtm: "GTM-04:00", city: "EST5EDT" },
  { offset: "+02", gtm: "GTM+02:00", city: "Egypt" },
  { offset: "+01", gtm: "GTM+01:00", city: "Eire" },
  { offset: "+00", gtm: "GTM+00:00", city: "Etc/GMT" },
  { offset: "+00", gtm: "GTM+00:00", city: "Etc/GMT+0" },
  { offset: "-01", gtm: "GTM-01:00", city: "Etc/GMT+1" },
  { offset: "-10", gtm: "GTM-10:00", city: "Etc/GMT+10" },
  { offset: "-11", gtm: "GTM-11:00", city: "Etc/GMT+11" },
  { offset: "-12", gtm: "GTM-12:00", city: "Etc/GMT+12" },
  { offset: "-02", gtm: "GTM-02:00", city: "Etc/GMT+2" },
  { offset: "-03", gtm: "GTM-03:00", city: "Etc/GMT+3" },
  { offset: "-04", gtm: "GTM-04:00", city: "Etc/GMT+4" },
  { offset: "-05", gtm: "GTM-05:00", city: "Etc/GMT+5" },
  { offset: "-06", gtm: "GTM-06:00", city: "Etc/GMT+6" },
  { offset: "-07", gtm: "GTM-07:00", city: "Etc/GMT+7" },
  { offset: "-08", gtm: "GTM-08:00", city: "Etc/GMT+8" },
  { offset: "-09", gtm: "GTM-09:00", city: "Etc/GMT+9" },
  { offset: "+00", gtm: "GTM+00:00", city: "Etc/GMT-0" },
  { offset: "+01", gtm: "GTM+01:00", city: "Etc/GMT-1" },
  { offset: "+10", gtm: "GTM+10:00", city: "Etc/GMT-10" },
  { offset: "+11", gtm: "GTM+11:00", city: "Etc/GMT-11" },
  { offset: "+12", gtm: "GTM+12:00", city: "Etc/GMT-12" },
  { offset: "+13", gtm: "GTM+13:00", city: "Etc/GMT-13" },
  { offset: "+14", gtm: "GTM+14:00", city: "Etc/GMT-14" },
  { offset: "+02", gtm: "GTM+02:00", city: "Etc/GMT-2" },
  { offset: "+03", gtm: "GTM+03:00", city: "Etc/GMT-3" },
  { offset: "+04", gtm: "GTM+04:00", city: "Etc/GMT-4" },
  { offset: "+05", gtm: "GTM+05:00", city: "Etc/GMT-5" },
  { offset: "+06", gtm: "GTM+06:00", city: "Etc/GMT-6" },
  { offset: "+07", gtm: "GTM+07:00", city: "Etc/GMT-7" },
  { offset: "+08", gtm: "GTM+08:00", city: "Etc/GMT-8" },
  { offset: "+09", gtm: "GTM+09:00", city: "Etc/GMT-9" },
  { offset: "+00", gtm: "GTM+00:00", city: "Etc/GMT0" },
  { offset: "+00", gtm: "GTM+00:00", city: "Etc/Greenwich" },
  { offset: "+00", gtm: "GTM+00:00", city: "Etc/UCT" },
  { offset: "+00", gtm: "GTM+00:00", city: "Etc/UTC" },
  { offset: "+00", gtm: "GTM+00:00", city: "Etc/Universal" },
  { offset: "+00", gtm: "GTM+00:00", city: "Etc/Zulu" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Amsterdam",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Andorra" },
  {
    offset: "+04",
    gtm: "GTM+04:00",
    city: "Europe/Astrakhan",
  },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Athens" },
  { offset: "+01", gtm: "GTM+01:00", city: "Europe/Belfast" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Belgrade",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Berlin" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Bratislava",
  },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Brussels",
  },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Europe/Bucharest",
  },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Budapest",
  },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Busingen",
  },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Europe/Chisinau",
  },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Copenhagen",
  },
  { offset: "+01", gtm: "GTM+01:00", city: "Europe/Dublin" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Gibraltar",
  },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Europe/Guernsey",
  },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Europe/Helsinki",
  },
  {
    offset: "+01",
    gtm: "GTM+01:00",
    city: "Europe/Isle_of_Man",
  },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Europe/Istanbul",
  },
  { offset: "+01", gtm: "GTM+01:00", city: "Europe/Jersey" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Kaliningrad",
  },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Kiev" },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Kirov" },
  { offset: "+01", gtm: "GTM+01:00", city: "Europe/Lisbon" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Ljubljana",
  },
  { offset: "+01", gtm: "GTM+01:00", city: "Europe/London" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Luxembourg",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Madrid" },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Malta" },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Europe/Mariehamn",
  },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Minsk" },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Monaco" },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Moscow" },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Nicosia" },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Oslo" },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Paris" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Podgorica",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Prague" },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Riga" },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Rome" },
  { offset: "+04", gtm: "GTM+04:00", city: "Europe/Samara" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/San_Marino",
  },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Sarajevo",
  },
  { offset: "+04", gtm: "GTM+04:00", city: "Europe/Saratov" },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Europe/Simferopol",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Skopje" },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Sofia" },
  {
    offset: "+02",
    gtm: "GTM+02:00",
    city: "Europe/Stockholm",
  },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Tallinn" },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Tirane" },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Europe/Tiraspol",
  },
  {
    offset: "+04",
    gtm: "GTM+04:00",
    city: "Europe/Ulyanovsk",
  },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Europe/Uzhgorod",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Vaduz" },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Vatican" },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Vienna" },
  { offset: "+03", gtm: "GTM+03:00", city: "Europe/Vilnius" },
  {
    offset: "+04",
    gtm: "GTM+04:00",
    city: "Europe/Volgograd",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Warsaw" },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Zagreb" },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Europe/Zaporozhye",
  },
  { offset: "+02", gtm: "GTM+02:00", city: "Europe/Zurich" },
  { offset: "+01", gtm: "GTM+01:00", city: "GB" },
  { offset: "+01", gtm: "GTM+01:00", city: "GB-Eire" },
  { offset: "+00", gtm: "GTM+00:00", city: "GMT" },
  { offset: "+00", gtm: "GTM+00:00", city: "GMT+0" },
  { offset: "+00", gtm: "GTM+00:00", city: "GMT-0" },
  { offset: "+00", gtm: "GTM+00:00", city: "GMT0" },
  { offset: "+00", gtm: "GTM+00:00", city: "Greenwich" },
  { offset: "-10", gtm: "GTM-10:00", city: "HST" },
  { offset: "+08", gtm: "GTM+08:00", city: "Hongkong" },
  { offset: "+00", gtm: "GTM+00:00", city: "Iceland" },
  {
    offset: "+03",
    gtm: "GTM+03:00",
    city: "Indian/Antananarivo",
  },
  { offset: "+06", gtm: "GTM+06:00", city: "Indian/Chagos" },
  {
    offset: "+07",
    gtm: "GTM+07:00",
    city: "Indian/Christmas",
  },
  { offset: "+06", gtm: "GTM+06:30", city: "Indian/Cocos" },
  { offset: "+03", gtm: "GTM+03:00", city: "Indian/Comoro" },
  {
    offset: "+05",
    gtm: "GTM+05:00",
    city: "Indian/Kerguelen",
  },
  { offset: "+04", gtm: "GTM+04:00", city: "Indian/Mahe" },
  {
    offset: "+05",
    gtm: "GTM+05:00",
    city: "Indian/Maldives",
  },
  {
    offset: "+04",
    gtm: "GTM+04:00",
    city: "Indian/Mauritius",
  },
  { offset: "+03", gtm: "GTM+03:00", city: "Indian/Mayotte" },
  { offset: "+04", gtm: "GTM+04:00", city: "Indian/Reunion" },
  { offset: "+04", gtm: "GTM+04:30", city: "Iran" },
  { offset: "+03", gtm: "GTM+03:00", city: "Israel" },
  { offset: "-05", gtm: "GTM-05:00", city: "Jamaica" },
  { offset: "+09", gtm: "GTM+09:00", city: "Japan" },
  { offset: "+12", gtm: "GTM+12:00", city: "Kwajalein" },
  { offset: "+02", gtm: "GTM+02:00", city: "Libya" },
  { offset: "+02", gtm: "GTM+02:00", city: "MET" },
  { offset: "-07", gtm: "GTM-07:00", city: "MST" },
  { offset: "-06", gtm: "GTM-06:00", city: "MST7MDT" },
  {
    offset: "-07",
    gtm: "GTM-07:00",
    city: "Mexico/BajaNorte",
  },
  { offset: "-06", gtm: "GTM-06:00", city: "Mexico/BajaSur" },
  { offset: "-05", gtm: "GTM-05:00", city: "Mexico/General" },
  { offset: "+12", gtm: "GTM+12:00", city: "NZ" },
  { offset: "+12", gtm: "GTM+12:45", city: "NZ-CHAT" },
  { offset: "-06", gtm: "GTM-06:00", city: "Navajo" },
  { offset: "+08", gtm: "GTM+08:00", city: "PRC" },
  { offset: "-07", gtm: "GTM-07:00", city: "PST8PDT" },
  { offset: "+13", gtm: "GTM+13:00", city: "Pacific/Apia" },
  {
    offset: "+12",
    gtm: "GTM+12:00",
    city: "Pacific/Auckland",
  },
  {
    offset: "+11",
    gtm: "GTM+11:00",
    city: "Pacific/Bougainville",
  },
  {
    offset: "+12",
    gtm: "GTM+12:45",
    city: "Pacific/Chatham",
  },
  { offset: "+10", gtm: "GTM+10:00", city: "Pacific/Chuuk" },
  { offset: "-06", gtm: "GTM-06:00", city: "Pacific/Easter" },
  { offset: "+11", gtm: "GTM+11:00", city: "Pacific/Efate" },
  {
    offset: "+13",
    gtm: "GTM+13:00",
    city: "Pacific/Enderbury",
  },
  {
    offset: "+13",
    gtm: "GTM+13:00",
    city: "Pacific/Fakaofo",
  },
  { offset: "+12", gtm: "GTM+12:00", city: "Pacific/Fiji" },
  {
    offset: "+12",
    gtm: "GTM+12:00",
    city: "Pacific/Funafuti",
  },
  {
    offset: "-06",
    gtm: "GTM-06:00",
    city: "Pacific/Galapagos",
  },
  {
    offset: "-09",
    gtm: "GTM-09:00",
    city: "Pacific/Gambier",
  },
  {
    offset: "+11",
    gtm: "GTM+11:00",
    city: "Pacific/Guadalcanal",
  },
  { offset: "+10", gtm: "GTM+10:00", city: "Pacific/Guam" },
  {
    offset: "-10",
    gtm: "GTM-10:00",
    city: "Pacific/Honolulu",
  },
  {
    offset: "-10",
    gtm: "GTM-10:00",
    city: "Pacific/Johnston",
  },
  {
    offset: "+14",
    gtm: "GTM+14:00",
    city: "Pacific/Kiritimati",
  },
  { offset: "+11", gtm: "GTM+11:00", city: "Pacific/Kosrae" },
  {
    offset: "+12",
    gtm: "GTM+12:00",
    city: "Pacific/Kwajalein",
  },
  { offset: "+12", gtm: "GTM+12:00", city: "Pacific/Majuro" },
  {
    offset: "-09",
    gtm: "GTM-09:30",
    city: "Pacific/Marquesas",
  },
  { offset: "-11", gtm: "GTM-11:00", city: "Pacific/Midway" },
  { offset: "+12", gtm: "GTM+12:00", city: "Pacific/Nauru" },
  { offset: "-11", gtm: "GTM-11:00", city: "Pacific/Niue" },
  {
    offset: "+11",
    gtm: "GTM+11:00",
    city: "Pacific/Norfolk",
  },
  { offset: "+11", gtm: "GTM+11:00", city: "Pacific/Noumea" },
  {
    offset: "-11",
    gtm: "GTM-11:00",
    city: "Pacific/Pago_Pago",
  },
  { offset: "+09", gtm: "GTM+09:00", city: "Pacific/Palau" },
  {
    offset: "-08",
    gtm: "GTM-08:00",
    city: "Pacific/Pitcairn",
  },
  {
    offset: "+11",
    gtm: "GTM+11:00",
    city: "Pacific/Pohnpei",
  },
  { offset: "+11", gtm: "GTM+11:00", city: "Pacific/Ponape" },
  {
    offset: "+10",
    gtm: "GTM+10:00",
    city: "Pacific/Port_Moresby",
  },
  {
    offset: "-10",
    gtm: "GTM-10:00",
    city: "Pacific/Rarotonga",
  },
  { offset: "+10", gtm: "GTM+10:00", city: "Pacific/Saipan" },
  { offset: "-11", gtm: "GTM-11:00", city: "Pacific/Samoa" },
  { offset: "-10", gtm: "GTM-10:00", city: "Pacific/Tahiti" },
  { offset: "+12", gtm: "GTM+12:00", city: "Pacific/Tarawa" },
  {
    offset: "+13",
    gtm: "GTM+13:00",
    city: "Pacific/Tongatapu",
  },
  { offset: "+10", gtm: "GTM+10:00", city: "Pacific/Truk" },
  { offset: "+12", gtm: "GTM+12:00", city: "Pacific/Wake" },
  { offset: "+12", gtm: "GTM+12:00", city: "Pacific/Wallis" },
  { offset: "+10", gtm: "GTM+10:00", city: "Pacific/Yap" },
  { offset: "+02", gtm: "GTM+02:00", city: "Poland" },
  { offset: "+01", gtm: "GTM+01:00", city: "Portugal" },
  { offset: "+08", gtm: "GTM+08:00", city: "ROC" },
  { offset: "+09", gtm: "GTM+09:00", city: "ROK" },
  { offset: "+08", gtm: "GTM+08:00", city: "Singapore" },
  { offset: "+03", gtm: "GTM+03:00", city: "Turkey" },
  { offset: "+00", gtm: "GTM+00:00", city: "UCT" },
  { offset: "-08", gtm: "GTM-08:00", city: "US/Alaska" },
  { offset: "-09", gtm: "GTM-09:00", city: "US/Aleutian" },
  { offset: "-07", gtm: "GTM-07:00", city: "US/Arizona" },
  { offset: "-05", gtm: "GTM-05:00", city: "US/Central" },
  {
    offset: "-04",
    gtm: "GTM-04:00",
    city: "US/East-Indiana",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "US/Eastern" },
  { offset: "-10", gtm: "GTM-10:00", city: "US/Hawaii" },
  {
    offset: "-05",
    gtm: "GTM-05:00",
    city: "US/Indiana-Starke",
  },
  { offset: "-04", gtm: "GTM-04:00", city: "US/Michigan" },
  { offset: "-06", gtm: "GTM-06:00", city: "US/Mountain" },
  { offset: "-07", gtm: "GTM-07:00", city: "US/Pacific" },
  { offset: "-07", gtm: "GTM-07:00", city: "US/Pacific-New" },
  { offset: "-11", gtm: "GTM-11:00", city: "US/Samoa" },
  { offset: "+00", gtm: "GTM+00:00", city: "UTC" },
  { offset: "+00", gtm: "GTM+00:00", city: "Universal" },
  { offset: "+03", gtm: "GTM+03:00", city: "W-SU" },
  { offset: "+01", gtm: "GTM+01:00", city: "WET" },
  { offset: "+00", gtm: "GTM+00:00", city: "Zulu" },
];
